management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
app:
  services:
    value:
      port: 8181
      url: http://localhost:${app.services.value.port}/valor/{id}